# xml : html처럼 태그 기반으로 자료를 저장한 포멧
- xml parser를 통해서 str을 xml로 변환하는 작업이 필요
- xml로 변환이 되면 태그 기반으로 자료를 찾아서 정리
- 태그에서 자료를 추출할 때는  beautifulsoup이라는 라이브러리를 이용

## JSON으로 가져오기

In [1]:
import os
import time
import requests
import pandas as pd

In [2]:
decoding_key = 'LVR82OMbkY0s4ySfvPsAAzVklADnEDLtwD4dgRH/T434bdVKyQhzWZew+9q669ncqTMgLzDna1iE7u4OTUKPGg=='

In [3]:
url = 'http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list'
payload = dict(serviceKey=decoding_key, numOfRows=100, pageNo=1, dataType='json')
r = requests.get(url,params=payload)

In [4]:
print(r.url)
print(r.status_code)

data = r.json()
# data

http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list?serviceKey=LVR82OMbkY0s4ySfvPsAAzVklADnEDLtwD4dgRH%2FT434bdVKyQhzWZew%2B9q669ncqTMgLzDna1iE7u4OTUKPGg%3D%3D&numOfRows=100&pageNo=1&dataType=json
200

In [5]:
result = {}
for i in range(len(data['body']['items'])):
#     print(i)
        for key, value in data['body']['items'][i].items():
#             print(key, value)
            result.setdefault(key, []).append(value)
# print(result)

result_df = pd.DataFrame(result)
result_df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250324,0,0,0,0,0,0,0,0,20250330,산업은행,1588-1500
1,20250324,0,0,0,0,0,0,0,0,20250330,제주은행,1588-0079
2,20250324,0,0,0,0,0,0,0,0,20250330,SC은행,1588-1599
3,20250324,0,0,0,0,0,0,0,0,20250330,경남은행,1588-8585
4,20250324,0,0,0,0,0,0,0,0,20250330,수협은행,1588-1515
5,20250324,4.28,0,0,0,0,0,0,0,20250330,우리은행,1599-5000
6,20250324,4.76,0,0,0,0,0,0,0,20250330,전북은행,1588-4477
7,20250324,3.54,0,0,0,0,0,0,0,20250330,카카오뱅크,1599-3333
8,20250324,3.32,0,0,0,0,0,0,0,20250330,아이엠뱅크,1588-5050
9,20250324,4.19,0,0,0,0,0,0,0,20250330,하나은행,1599-1111
10,20250324,3.64,0,0,0,0,0,0,0,20250330,토스뱅크,1661-7654
11,20250324,3.62,0,0,0,0,0,0,0,20250330,케이뱅크,1522-1000
12,20250324,3.76,0,0,0,0,0,0,0,20250330,기업은행,1566-2566
13,20250324,3.7,0,0,0,0,0,0,0,20250330,부산은행,1588-6200
14,20250324,3.97,0,0,0,0,0,0,0,20250330,농협은행,1588-2100
15,20250324,3.8,0,0,0,0,0,0,0,20250330,국민은행,1644-9999
16,20250324,4.17,0,0,0,0,0,0,0,20250330,광주은행,1600-4000
17,20250324,4.09,0,0,0,0,0,0,0,20250330,신한은행,1599-8000

## xml로 가져오기
### xml로 추출된 데이터
- xml로 데이터를 받으면 처음에는 단순 문자열을 받게 됨
- 문자열을 xml 문서 변환 필요
- beautifulsoup을 이용해 xml 문서로 변환
- HTML과 XML 파일로부터 데이터를 뽑아내기 위한 파이썬 라이브러리
- beautifulsoup의 메서드인 select, select_one을 이용
    - css 셀렉터 기반으로 데이터가 위치한 태그 찾아서 내용 추출

In [6]:
url = 'http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list'
payload = dict(serviceKey=decoding_key, numOfRows=100, pageNo=1, dataType='xml')
r_xml = requests.get(url,params=payload)

In [7]:
print(r_xml.url)
print(r_xml.status_code)

# 데이터가 각 태그 안에 존재
# print(r_xml.text)

http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list?serviceKey=LVR82OMbkY0s4ySfvPsAAzVklADnEDLtwD4dgRH%2FT434bdVKyQhzWZew%2B9q669ncqTMgLzDna1iE7u4OTUKPGg%3D%3D&numOfRows=100&pageNo=1&dataType=xml
200

# Beautifulsoup : 문자열을 DOM TREE 구조로 변환
[beautifulsoup 참고 페이지](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)

- pip install beautifulsoup4
- form bs4 import BesutifulSoup as bs

----
- find, find all 함수 : xml, html 태그 기반으로 내용을 찾음
- select, select_one 함수 : xml, hteml에서 css selector 기반으로 내용 찾음
- find_all, select는 해당 태그나 css selector를 가진 부분을 모두 찾아서 list로 반환
- find, select_one은 여러 태그나 css selector 중에서 가장 먼저 나오는 태그/selector를 한 개만 찾아줌
- 찾아온 태그 .name : 태그 이름 반환
- 찾아온 태그 . text, .string :  태그 안쪽의 텍스트 반환

In [8]:
# !pip install beautifulsoup4
# cmd > conda install beautifulsoup4

In [8]:
from bs4 import BeautifulSoup as bs

In [9]:
soup = bs(r_xml.text, 'xml')
# print(soup)

In [10]:
items = soup.select_one('items')
bssYmdStart_list = items.select('bssYmdStart')
interest4_1_list = items.select('interest4_1')
interest3_2_list = items.select('interest3_2')
interest4_2_list = items.select('interest4_2')
interest2_1_list = items.select('interest2_1')
interest1_2_list = items.select('interest1_2')
interest3_1_list = items.select('interest3_1')
interest2_2_list = items.select('interest2_2')
interest1_1_list = items.select('interest1_1')
bssYmdEnd_list = items.select('bssYmdEnd')
organId_list = items.select('organId')
callCenter_list = items.select('callCenter')

In [11]:
tag_list = [bssYmdStart_list, interest4_1_list, interest3_2_list, interest4_2_list, interest3_1_list, interest2_2_list, interest1_1_list, bssYmdEnd_list, organId_list, callCenter_list]

In [12]:
result = {}
for lists in tag_list:
    for item in lists:
        result.setdefault(item.name, []).append(item.text)
# print(result)

In [13]:
final_df = pd.DataFrame(result)
final_df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250324,0,0,0,0,0,0,20250330,산업은행,1588-1500
1,20250324,0,0,0,0,0,0,20250330,제주은행,1588-0079
2,20250324,0,0,0,0,0,0,20250330,SC은행,1588-1599
3,20250324,0,0,0,0,0,0,20250330,경남은행,1588-8585
4,20250324,0,0,0,0,0,0,20250330,수협은행,1588-1515
5,20250324,4.28,0,0,0,0,0,20250330,우리은행,1599-5000
6,20250324,4.76,0,0,0,0,0,20250330,전북은행,1588-4477
7,20250324,3.54,0,0,0,0,0,20250330,카카오뱅크,1599-3333
8,20250324,3.32,0,0,0,0,0,20250330,아이엠뱅크,1588-5050
9,20250324,4.19,0,0,0,0,0,20250330,하나은행,1599-1111
10,20250324,3.64,0,0,0,0,0,20250330,토스뱅크,1661-7654
11,20250324,3.62,0,0,0,0,0,20250330,케이뱅크,1522-1000
12,20250324,3.76,0,0,0,0,0,20250330,기업은행,1566-2566
13,20250324,3.7,0,0,0,0,0,20250330,부산은행,1588-6200
14,20250324,3.97,0,0,0,0,0,20250330,농협은행,1588-2100
15,20250324,3.8,0,0,0,0,0,20250330,국민은행,1644-9999
16,20250324,4.17,0,0,0,0,0,20250330,광주은행,1600-4000
17,20250324,4.09,0,0,0,0,0,20250330,신한은행,1599-8000

## 반복문으로 태그를 자동 추출해서 만들기

In [20]:
result = {}
for item in soup.select('items'):
    for tags in item.select('item'):
#         print(tags)
        for tag in tags:
            result.setdefault(tag.name, []).append(tag.text)
# print(result)

df = pd.DataFrame(result)
df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111
10,20250310,3.74,0,0,0,0,0,0,0,20250316,토스뱅크,1661-7654
11,20250310,3.7,0,0,0,0,0,0,0,20250316,케이뱅크,1522-1000
12,20250310,3.89,0,0,0,0,0,0,0,20250316,국민은행,1644-9999
13,20250310,3.84,0,0,0,0,0,0,0,20250316,부산은행,1588-6200
14,20250310,4.05,0,0,0,0,0,0,0,20250316,농협은행,1588-2100
15,20250310,4.0,0,0,0,0,0,0,0,20250316,기업은행,1566-2566
16,20250310,4.11,0,0,0,0,0,0,0,20250316,광주은행,1600-4000
17,20250310,4.07,0,0,0,0,0,0,0,20250316,신한은행,1599-8000

In [28]:
# soup.select('item')

# xml에 있는 모든 key 추출

## set : 집합자료형
- 중복 없는 데이터 집합 생성

In [249]:
tag_names = []
for items in soup.select('item'):
    for item in items:
        tag_names.append(item.name)
# tag_names

tags = set(tag_names)
tags

{'bssYmdEnd',
 'bssYmdStart',
 'callCenter',
 'interest1_1',
 'interest1_2',
 'interest2_1',
 'interest2_2',
 'interest3_1',
 'interest3_2',
 'interest4_1',
 'interest4_2',
 'organId'}

# 공공데이터_서민대출상품 취급기관 정보 서비스

In [29]:
Decoding = 'LVR82OMbkY0s4ySfvPsAAzVklADnEDLtwD4dgRH/T434bdVKyQhzWZew+9q669ncqTMgLzDna1iE7u4OTUKPGg=='

In [71]:
url = 'https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo'
payload = dict(serviceKey=Decoding, numOfRows=100, pageNo=1, resultType='xml')
r = requests.get(url, params = payload)

In [72]:
print(r.url)
print(r.status_code)
# print(r.text)

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=LVR82OMbkY0s4ySfvPsAAzVklADnEDLtwD4dgRH%2FT434bdVKyQhzWZew%2B9q669ncqTMgLzDna1iE7u4OTUKPGg%3D%3D&numOfRows=100&pageNo=1&resultType=xml
200

In [250]:
soup = bs(r.text, 'xml')
# print(soup)

In [253]:
# 모든 key 추출
tag_name = []
for items in soup.select('item'):
#     print(items)
    for item in items:
#         print(item.name)
        tag_name.append(item.name)

tag_name = set(tag_name)
tag_name

{None,
 'age',
 'anin',
 'basYm',
 'cnpl',
 'crdtSc',
 'cv19Rfrc',
 'cv19SuprCtg',
 'cv19SuprCtn',
 'cv19SuprTgtDtlCtn',
 'etcRefSbjc',
 'fileWrtDt',
 'finPrdNm',
 'grnInst',
 'hdlInst',
 'hdlInstDtlVw',
 'housAr',
 'housHoldCnt',
 'incm',
 'instCtg',
 'irt',
 'irtCtg',
 'jnMthd',
 'lnIcdcst',
 'lnLmt',
 'lnTgtHous',
 'maxDfrmTrm',
 'maxRdptTrm',
 'maxTotLnTrm',
 'mgmDln',
 'ofrInstNm',
 'ovItrYr',
 'prdCtg',
 'prdCtg2',
 'prdExisYn',
 'prdNm',
 'prftAddIrtCond',
 'rdptMthd',
 'rfrcCnpl',
 'rltSite',
 'rpymdCfe',
 'rsdArea',
 'rsdAreaPamtEqltIstm',
 'snq',
 'suprTgtDtlCond',
 'tgtFltr',
 'trgt',
 'usge'}

In [251]:
result = {}
for items in soup.select('items'):
    for item in items('item'):
#         print(item)
        for tag in item:
#             print(tag.name)
            if tag.name is None:
                continue
            result.setdefault(tag.name, []).append(tag.text)
# print(result)

result_df = pd.DataFrame(result)
result_df

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,202503,97,경상북도 낙동강론,1500만원,고정금리,2.0~4.0%,5년,0년,5년,원리금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
96,202503,98,LH공사 행복론,1500만원,고정금리,2.0~4.0%,5년,0년,5년,원리금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
97,202503,99,광주광역시 빛고을론,1500만원,고정금리,2.0~ 3.5%,5년,0년,5년,원리금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
98,202503,100,인천광역시 어진론,1500만원,고정금리,2.0~3.5%,5년,0년,5년,원리금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
99,202503,101,서울특별시 한강론,1500만원,고정금리,2~3%,5년,0년,5년,원리금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700

In [254]:
for i in soup('totalCount'):
    n_count = i.text
    total_pages = (int(i.text)//100)+1
print(n_count, total_pages)

4741 48

In [255]:
import time

url = 'https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo'
payload = dict(serviceKey=Decoding, numOfRows=1, pageNo=1, resultType='xml')
r = requests.get(url, params=payload)
soup = bs(r.text, 'xml')

total_counts = int(soup.find('totalCount').text)
total_pages = (total_counts // 100) + 1
print(f"총 데이터: {total_counts}, 총 페이지: {total_pages}")

page_xml = {}
page = 1
nums = 100

while True:
    print(f"{page}/{total_pages} 수집중", end='\r')
    
    if page == total_pages:
        nums = total_counts - (page - 1) * 100
    
    payload = dict(serviceKey=Decoding, numOfRows=nums, pageNo=page, resultType='xml')
    r = requests.get(url, params=payload)
    soup = bs(r.text, 'xml')
    
    for items in soup.select('items'):
        for item in items('item'):
            for tag in item:
                if tag.name is None:
                    continue
                page_xml.setdefault(tag.name, []).append(tag.text)
    

    if page * 100 >= total_counts:
        break
    page += 1
    time.sleep(0.1)


print(f"\n수집 완료: {total_pages} 페이지")

총 데이터: 4741, 총 페이지: 48
48/48 수집중
수집 완료: 48 페이지

In [256]:
df_loan_info = pd.DataFrame(page_xml)
df_loan_info

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4736,202201,79,전세입주보증금,2000만원,고정금리,0%,3년,0년,3년,만기일시상환,...,Y,,1,대출상품,,,,연중 수시접수,지자체·복지,202201040923
4737,202201,80,주민소득지원자금융자,3000만원,고정금리,2%,5년,2년,3년,균등분할상환,...,Y,,1,대출상품,,,,연도마다 신청기간 상이(기관 문의),지자체·복지,202201040923
4738,202201,81,주민복지지원사업 융자,1000만원,고정금리,1.0%,7년,2년,5년,균등분할상환,...,Y,,1,대출상품,,,,연도마다 신청기간 상이(기관 문의),지자체·복지,202201040923
4739,202201,82,기초생활보장기금 융자금,1000,고정금리,1%,5년,0년,5년,"균등분할상환, 만기일시상환",...,Y,,1,대출상품,,,,기관 문의,지자체·복지,202201040923
4740,202201,83,기초생활보장기금 융자지원,2000만원,고정금리,1%,5년,2년,3년,분할상환,...,Y,,1,대출상품,,,,기관 문의,지자체·복지,202201040923

## XML 데이터 정리하기

In [258]:
xml_result_df_list = []
page = 1

while True:
    Decoding = 'LVR82OMbkY0s4ySfvPsAAzVklADnEDLtwD4dgRH/T434bdVKyQhzWZew+9q669ncqTMgLzDna1iE7u4OTUKPGg=='
    url = 'https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo'
    payload = dict(serviceKey=Decoding, numOfRows=100, pageNo=page, resultType='xml')
    r = requests.get(url, params = payload)
#     print(r.url)
#     print(r.status_code)

    response = r.content
    soup = bs(response, 'xml')

    xml_result = {}
    for item in soup.select('item'):
        for tags in item:
            if tags.name == None:
                continue
            else:
                xml_result.setdefault(tags.name, []).append(tags.text)

    xml_result_df_list.append(pd.DataFrame(xml_result))
    numOfRows = int(soup.select_one("numOfRows").text)
    totalCount = int(soup.select_one("totalCount").text)
    total_pages = totalCount // numOfRows + 1
    if page < total_pages:
        page += 1
    else:
        break
        
xml_result_df_list = pd.concat(xml_result_df_list)
xml_result_df_list = xml_result_df_list.reset_index(drop=True)
xml_result_df_list

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4736,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4737,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4738,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4739,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,,1,대출상품,,,,,,202502010700
4740,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700

- setdefault를 아용해 xml의 tag명의 유일값 추출

In [202]:
tag_names = {}
for tags in soup.select('*'):
#     print(tags.name)
    tag_names.setdefault(tags.name, '')
# print(tag_names)
for tag_name in tag_names:
    print(f"'{tag_name}'", end=' ')

'response' 'header' 'resultCode' 'resultMsg' 'body' 'numOfRows' 'pageNo' 'totalCount' 'items' 'item' 'basYm' 'snq' 'finPrdNm' 'lnLmt' 'irtCtg' 'irt' 'maxTotLnTrm' 'maxDfrmTrm' 'maxRdptTrm' 'rdptMthd' 'usge' 'trgt' 'instCtg' 'ofrInstNm' 'rsdAreaPamtEqltIstm' 'suprTgtDtlCond' 'age' 'incm' 'rsdArea' 'crdtSc' 'anin' 'housHoldCnt' 'housAr' 'lnTgtHous' 'rfrcCnpl' 'grnInst' 'jnMthd' 'rpymdCfe' 'lnIcdcst' 'ovItrYr' 'prftAddIrtCond' 'etcRefSbjc' 'hdlInst' 'cnpl' 'rltSite' 'tgtFltr' 'hdlInstDtlVw' 'prdExisYn' 'cv19Rfrc' 'prdCtg' 'prdNm' 'cv19SuprCtg' 'cv19SuprCtn' 'cv19SuprTgtDtlCtn' 'mgmDln' 'prdCtg2' 'fileWrtDt'

## key_list를 만들고 select로 직접 수집하기

In [269]:
key_list = {}
for item in soup.select('*'):
    key_list.setdefault(item.name, '')
key_list = list(key_list.keys())
# key_list

In [270]:
keys = key_list[10:]

In [271]:
df_list = []
page = 1

while True:
    url = "https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
    service_key = "8Ym5dhmVJdr12XzGnyYrQjSBS1QuRBYK8yHfx65JCl4vACM9uLKo8fxCVOFJkPB71llD7F2rOEROZnHgNGoj3A=="
    payload = dict(serviceKey=service_key, numOfRows=100, pageNo=page, resultType='xml')
    r = requests.get(url, params=payload)
#     print(r.url)
#     print(r.status_code)

    response = r.content
    soup = bs(response, "xml")
    
    numOfRows = int(soup.select_one("numOfRows").text)
    totalCount = int(soup.select_one("totalCount").text)
    total_pages = totalCount // numOfRows + 1
    
    key_list = {}
    for item in soup.select("*"):
        key_list.setdefault(item.name, "")
    keys = list(key_list.keys())
    
    for key in keys[10:]:
        for item in soup.select(key):
            result.setdefault(item.name, []).append(item.text)
    df_list.append(pd.DataFrame(result))
    if page < total_pages:
        page += 1
    else:
        print("데이터 수집완료")
        break

result_df = pd.concat(df_list)
result_df = result_df.reset_index(drop=True)
result_df

In [237]:
result = {}
for key in keys:
#     print(soup.select(key))
    for item in soup.select(key):
#         print(item.name, item.text)
        result.setdefault(item.name, []).append(item.text)
# print(result)

result_df = pd.DataFrame(result)
result_df

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,202503,97,경상북도 낙동강론,1500만원,고정금리,2.0~4.0%,5년,0년,5년,원리금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
96,202503,98,LH공사 행복론,1500만원,고정금리,2.0~4.0%,5년,0년,5년,원리금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
97,202503,99,광주광역시 빛고을론,1500만원,고정금리,2.0~ 3.5%,5년,0년,5년,원리금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
98,202503,100,인천광역시 어진론,1500만원,고정금리,2.0~3.5%,5년,0년,5년,원리금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
99,202503,101,서울특별시 한강론,1500만원,고정금리,2~3%,5년,0년,5년,원리금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700